[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://demoblog.site/*"
  to = "https://www.demoblog.site/:splat"
  status = 301
  force = true