import './globals.css';
import { Suspense } from 'react';

import { MessageProvider } from '@/context/MessageContext';

import Loading from '../components/Loading';
import MessageDisplay from '../components/MessageDisplay';

import Footer from './Footer';
import Header from './Header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Demo Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <MessageProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-grow">
              <Suspense fallback={<Loading />}>
                <MessageDisplay />
                {children}
              </Suspense>
            </main>
            <Footer />
          </div>
        </MessageProvider>
      </body>
    </html>
  );
}
